### ISSUE TITLE
Better flat tree handling

### ISSUE THREAD

**Issue by daedalus28** [smartprocure/contexture-client#131]
Right now `flat` does not use the parameterized object init/extend props and is just a plain JS object. In a mobx context, this means that you can't rely on the flat tree being observable. This might be ok - one perspective is that `flat` is really an implementation detail anyway and should be private. For now, the answer is not to rely on `flat` (and, in most cases so far, doing so is a better and simpler implementation for end-users anyway).

This ticket is a placeholder for discussion on the topic. We've also considered removing the internal `flat` tree, which might be the best option - it's effectively a performance optimization that hasn't ever proven to be needed.

**Comment by rma4ok** [comment]
We are currenly using `tree.flat` in contexture-react [FilterList](https://github.com/smartprocure/contexture-react/blob/master/src/FilterList.js#L167)
Just using it as a cached flat tree for performance reasons. There are no `flat` observers

**Comment by daedalus28** [comment]
> We are currenly using `tree.flat` in contexture-react [FilterList](https://github.com/smartprocure/contexture-react/blob/master/src/FilterList.js#L167) Just using it as a cached flat tree for performance reasons. There are no `flat` observers

#90 will provide a first-class API for this use case 👍
