### ISSUE TITLE
Also document the example client

### ISSUE THREAD

**Issue by sadasant** [smartprocure/contexture-client#36]
It was a neat small thing we used to have.

**Comment by daedalus28** [comment]
Taking this a part of the documentation work for contexture

**Comment by daedalus28** [comment]
This won't work for the general public, but for internal reference, marketplace PR 3209 is where you'll find the diffs

**Comment by daedalus28** [comment]
Just adding the diff here for more public consumption. The example client was really just about making the whole tree observable, creating a reaction that listens to any change except context, then making an API call to search and merging tree leaves. It doesn't do any of the fancy things the real client does and is only useful as a form of documentation to understand the basic idea of what this library does.

<img width="901" alt="Screen Shot 2022-04-20 at 7 47 54 PM" src="https://user-images.githubusercontent.com/1043503/164361668-1c5bd06e-b1b8-486d-8da2-5c91ce618639.png">

**Comment by daedalus28** [comment]
Closing this and rolling it in as part of #19
