### ISSUE TITLE
Mutate should be smarter

### ISSUE THREAD

**Issue by stellarhoof** [smartprocure/contexture-client#97]
It shouldn't run a search if nothing has changed. We could compare the new vs the old tree and only send a search if there are changes. We should also be careful not to run `onChange` if nothing has changed.

**Comment by stellarhoof** [comment]
Closing this. I don't even remember what I was talking about here :D

**Comment by daedalus28** [comment]
@stellarhoof this was about the fact that calling mutate on the same values still triggers an update, e.g.:

```js
await tree.mutate(['root', 'criteria', 'filtera'], { value: 12})
await tree.mutate(['root', 'criteria', 'filtera'], { value: 12})
```
Runs two searches :)

**Comment by daedalus28** [comment]
It's actually potentially in scope for the client to handle, but the UI components probably take care of the most common scenarios.

**Comment by stellarhoof** [comment]
Ohh got it. Reopening then :)

**Comment by daedalus28** [comment]
Specifically, we can compare `previous` to `value` here (or at least the fields that are in `value`): https://github.com/smartprocure/contexture-client/blob/master/src/actions/index.js#L69

**Comment by chris110408** [comment]
@daedalus28 is there any case we do need run calling mutate on the same values? should I add a flag to turn this function on or off?

**Comment by daedalus28** [comment]
> @daedalus28 is there any case we do need to call `mutate` on the same values? should I add a flag to turn this function on or off?

I don't think there's any case for duplicate mutates triggering updates. The role of contexture client is to optimize when to run searches - if the goal is to trigger another update for some reason, dispatching a refresh event is the way to go. The normal use of the core should be as optimized as possible.
